version: '3'

x-web_service: &web_service
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./output:/usr/src/app/output
      - ./whisper_model:/root/.cache/whisper
    environment:
      - WEB_ARGS= --port 5000
                  --max-size 1073741824

x-gpu: &gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
services:
  cpu:
    profiles: ["cpu"]
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: whisper_timestamped_cpu:latest
    tty: true

  gpu:
    <<: *gpu
    profiles: ["gpu"]
    build:
      context: .
      dockerfile: Dockerfile
    image: whisper_timestamped:latest
    tty: true

  web_cpu:
    <<: *web_service
    profiles: ["web-cpu"]
    build:
      context: .
      dockerfile: Dockerfile.webcpu
    image: whisper_timestamped_cpu:latest
    environment:
      - CLI_ARGS= --model tiny
                  --device cpu
                  --vad
                  --detect_disfluencies
                  --accurate

  web_gpu:
    <<: [*web_service,*gpu]
    profiles: ["web-gpu"]
    build:
      context: .
      dockerfile: Dockerfile.web
    image: whisper_timestamped:latest   
    environment:
      - CLI_ARGS= --model large
                  --device cuda:0
                  --vad
                  --detect_disfluencies
                  --accurate